<?php

namespace AppBundle\Repository;

/**
 * coworkerPhotoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class coworkerPhotoRepository extends \Doctrine\ORM\EntityRepository
{
}
