<?php

namespace AppBundle\Repository;

/**
 * indexPageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class indexPageRepository extends \Doctrine\ORM\EntityRepository
{
}
