<?php

namespace AppBundle\Repository;

/**
 * MentionLegaleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MentionLegaleRepository extends \Doctrine\ORM\EntityRepository
{
}
