<?php

namespace AppBundle\Repository;

/**
 * siteInfoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class siteInfoRepository extends \Doctrine\ORM\EntityRepository
{
}
