<?php

namespace AppBundle\Repository;

/**
 * titreIntroRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class titreIntroRepository extends \Doctrine\ORM\EntityRepository
{
}
